import type { Catalog } from '../catalog/types'

export function LicensesFooter({ catalog }: { catalog: Catalog | null }) {
  return (
    <footer className="licenses">
      <p>
        Icons come from open licensed sets, each keeping its own license:{' '}
        {catalog?.sets.map((set, index) => (
          <span key={set.id}>
            {index > 0 && ' · '}
            <a href={set.source} target="_blank" rel="noreferrer">
              {set.label}
            </a>{' '}
            ({set.license})
          </span>
        ))}
        . Brand icons from Simple Icons are subject to their owners' trademark policies — check them before shipping a brand
        mark as your app icon.
      </p>
      <p>
        Glass backgrounds are generated by this tool.{' '}
        <a href="https://github.com/roquerodrigo/glass-icons" target="_blank" rel="noreferrer">
          Source on GitHub
        </a>
        .
      </p>
    </footer>
  )
}
